### ISSUE TITLE
大家要不要建个群讨论一下

### ISSUE THREAD

**Issue by baobaotql** [wangle1218/KBQA-for-Diagnosis#20]
如题，大家一起讨论一下哇，围绕这个开源项目和相关算法探讨探讨。

**Comment by baobaotql** [comment]
> 找不到这个群啊

加我qq拉你进群 大家一起学习和讨论

**Comment by yangyangD-hub** [comment]
2049913691 谢谢

**Comment by xiaoxiong1234** [comment]
可以拉我一下吗，谢谢， 1576884075

**Comment by brooksxie** [comment]
> 如题，大家一起讨论一下哇，围绕这个开源项目和相关算法探讨探讨。

1126896871 谢谢

**Comment by MRpanda02** [comment]
> > 找不到这个群啊
> 
> 加我qq拉你进群 大家一起学习和讨论



> 如题，大家一起讨论一下哇，围绕这个开源项目和相关算法探讨探讨。

可以拉我一下吗，谢谢！ 819687198

**Comment by daily063** [comment]
> 如题，大家一起讨论一下哇，围绕这个开源项目和相关算法探讨探讨。

1291036109 可以拉一下吗？谢谢

**Comment by lxb11** [comment]
623417725 可以拉一下吗？谢谢

**Comment by YeLyea** [comment]
1758901975 可以拉一下吗？谢谢
