### ISSUE TITLE
entity_normalization - The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### ISSUE THREAD

**Issue by sshimii** [wangle1218/KBQA-for-Diagnosis#6]
实体标准化，训练完之后predict，在load_weights的地方报错
![image](https://user-images.githubusercontent.com/41730403/118960190-9c640b80-b995-11eb-819b-73d49781bb98.png)

**Comment by wangle1218** [comment]
checkpoint 文件夹里有模型权重文件吗，有的话看一下是否是正常的。。。

**Comment by sshimii** [comment]
> checkpoint 文件夹里有模型权重文件吗，有的话看一下是否是正常的。。。

找到原因啦，因为epoch太多，我中途停掉了，导致esim_model.json没有存储。谢谢大佬

**Comment by sshimii** [comment]
> checkpoint 文件夹里有模型权重文件吗，有的话看一下是否是正常的。。。

搞定啦，我用的是2.3.1版本的keras，应该是版本不一致导致的。修改了keras底层的代码之后，可以正常运行了。
![image](https://user-images.githubusercontent.com/41730403/119107935-4acd8680-ba52-11eb-9fdf-684037b7ab06.png)

**Comment by wangle1218** [comment]
现在加载权重文件这么复杂了么。。。。
