### ISSUE TITLE
slotgate_slu/train.py中的main函数，model_param['intent_nums']被赋值两次

### ISSUE THREAD

**Issue by sshimii** [wangle1218/KBQA-for-Diagnosis#7]
![image](https://user-images.githubusercontent.com/41730403/119288568-5f409780-bc7b-11eb-9cfb-27202c9733cd.png)
这边model_param['intent_nums']被赋值了两次，第二个是不是写错了

**Comment by wangle1218** [comment]
第二个是slot nums------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年5月24日(星期一) 上午10:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wangle1218/KBQA-for-Diagnosis] slotgate_slu/train.py中的main函数，model_param[&#39;intent_nums&#39;]被赋值两次 (#7)
